<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- 添加惯性属性 -->
  <xacro:include filename="$(find fishbot_description)/urdf/fishbot/common_inertia.xacro"/>
  <!-- 添加底盘惯性 -->
  <xacro:macro name="base_xacro" params="length radius">
    <!-- 虚拟地面 -->
    <link name="base_footprint"/>

    <!-- 小车底盘 -->
    <link name="base_link">
      <!-- 可视部分 -->
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <material name="white">
          <color rgba="1.0 1.0 1.0 0.5"/>
        </material>
      </visual>

      <!-- 碰撞部分 -->
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
      </collision>

      <!-- 添加惯性属性 -->
      <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}"/>
    </link>

    <!-- 虚拟地面与小车底盘之间的固定关节 -->
    <joint name="base_footprint_joint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <origin xyz="0 0 ${length/2+0.032-0.01}" rpy="0 0 0"/> 
    </joint>
  </xacro:macro>
</robot>